apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstc-akounting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cstc-akounting
  template:
    metadata:
      labels:
        app: cstc-akounting
    spec:
      containers:
      - name: cstc-akounting
        image: cstciiiichabir/cstc_akounting
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: akaunting-config
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: akaunting-secret
              key: DB_HOST
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: akaunting-secret
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: akaunting-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: akaunting-secret
              key: DB_PASSWORD
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: akaunting-secret
              key: APP_KEY
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: akaunting-secret
              key: MAIL_PASSWORD
      

