name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarScans:
    name: SonarScan PHP-${{ matrix.php }}
    runs-on: self-hosted

    strategy:
      matrix:
        php: ['8.1'] 

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # not bothering with PHP anymore
      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          #scannerBinariesUrl: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli
          projectBaseDir: .
          arguments: >
            -Dsonar.projectKey=CSTC_ACKOUNTING
            -Dsonar.sources=app,config,resources,routes,tests
            -Dsonar.exclusions=node_modules/**,public/**,storage/**,vendor/**
