name: SonarQube sacan

on:
  push:
    branches: 
      - main
jobs:
  sonarScans:
    name: SonarScan ${{  matrix.php  }}
    
    runs-on: self-hosted

    strategy:
      matrix:
        php: ['8.1']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
    #  - name: Setup PHP
    #    uses: shivammathur/setup-php@v2
    #    with:
    #      php-version: ${{ matrix.php }}
    #      extensions: bcmath, ctype, dom, fileinfo, intl, gd, json, mbstring, pdo, pdo_sqlite, openssl, sqlite, xml, zip
    #      coverage: none
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
            
          
        
