name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarScans:
    name: SonarScan PHP-${{ matrix.php }}
    runs-on: self-hosted

    strategy:
      matrix:
        php: ['8.1'] 

    steps:
      - name: Adding GitHub to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CSTX_SSH_KEY }}
          repository: ${{ github.repository }}
          submodules: true
        # not bothering with PHP anymore :)
      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=CSTC_ACKOUNTING
            -Dsonar.sources=app,config,resources,routes,tests
            -Dsonar.exclusions=node_modules/**,public/**,storage/**,vendor/**
            -Dsonar.analysis.mode=analysis
      # Let's Play > Getting our sonar quality 
      - name: SonarQube Quality Gate
        id: sonar_quality_gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
